name: Reorder Shopify Collections

on:
  workflow_dispatch:      # botón "Run workflow" en Actions
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC = 1:00 a. m. America/Mexico_City

jobs:
  reorder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Secrets
      SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
      SHOPIFY_ADMIN_TOKEN:  ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
      SHOPIFY_API_VERSION:  ${{ secrets.SHOPIFY_API_VERSION }}

      # Controles
      DRY_RUN: "false"                # ← cámbialo a "false" para aplicar en vivo
      INCLUDE_SMART: "true"          # incluye colecciones automáticas
      INCLUDE_MANUAL: "true"         # incluye colecciones manuales
      HANDLE_PREFIX: ""              # opcional: filtra por prefijo de handle

      # EXCLUSIONES (colecciones)
      EXCLUDE_COLLECTION_IDS: "648364163362"
      EXCLUDE_HANDLES: ""

      # Democión (enviar productos al final)
      DEMOTE_TITLE_KEYWORDS: "Cinturón,Calcetin,Boxer,Perfume,loción"
      DEMOTE_TAGS: "Cinturón,Calcetin,Biker,Perfume"
      DEMOTE_PRODUCT_TYPES: ""

      # Costo / velocidad
      MAX_PRODUCTS_PER_PAGE: "12"
      MAX_INVENTORY_LEVELS: "1"
      LOCATION_IDS: ""               # opcional: IDs de locations (coma-separadas)

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show repo files (debug)
        run: |
          pwd
          ls -la
          ls -la scripts || true

      - name: Run reorder script
        run: node scripts/reorder-all-collections.js
